# 📝 Ejercicios M03: Asentando Numpy y de paso Python

Comienza importando la librería Numpy:

In [1]:
import numpy as np

Crea un vector de 10 unos. 

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Crea un vector de 10 8s.

In [97]:
v=np.ones(10)
v8=v.copy()*8
v8


array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [100]:
np.ones(10) * 8  

array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

Crea un array con todos los valores pares del 0 al 20.

In [15]:
arr=np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Crea una matriz 3x3 con los valores del 1 al 9.

In [101]:
m=np.arange(1,10)
m.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Genera un lanzamiento de un dado aleatorio (valores entre 1 y 6)

In [29]:
dado=np.random.randint(1,7)
dado

2

Genera 100 lanzamiento de un dado aleatorio (valores entre 1 y 6) y devuelve la media

In [103]:
lanzs=np.random.randint(1,7,100)
media=lanzs.mean()
print(media)

3.49


In [104]:
np.random.randint(1,7,100).mean()

np.float64(3.63)

Crea la siguiente matriz:

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [105]:
matriz=np.array([[0,2,4,6],[8,10,12,14],[16,18,20,22]])
matriz


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [109]:
matrix=np.arange(0,23,2).reshape(3,4)
matrix

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [108]:
check=np.array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])


In [110]:
matrix==check

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [113]:
(matrix==check).sum()

np.int64(12)

Quédate con la submatriz:

array([[ 2,  4],
       [10, 12]])

In [115]:
submatriz=matriz[0:2,1:3]
submatriz

array([[ 2,  4],
       [10, 12]])

Obtén la suma de los valores de la última matriz.

In [99]:
submatriz.sum()

np.int64(28)

# 📝 Práctica M03: Evaluación de Estrés en Cartera Hipotecaria

**Escenario:** Eres el analista de riesgos de un banco. El Banco Central ha pedido un "Test de Estrés". Debes analizar una cartera de 5,000 préstamos y calcular cuánto dinero perdería el banco si las condiciones económicas empeoran.

## 🛠️ EJERCICIOS

**Ejercicio 1: Configuración de la Cartera (Creación de Datos)**

1. Genera un array con los Saldos Pendientes de 5,000 hipotecas. Los saldos deben ser valores aleatorios entre 50,000€ y 300,000€.
2. Genera un array con el LTV (Loan-to-Value) de cada hipoteca. El LTV es el porcentaje del valor de la casa que el banco prestó. Genera valores que sigan una distribución normal con media de 70% y desviación estándar de 10%.
3. Calcula el Valor de las Propiedades: Si el $LTV = \frac{Saldo}{Valor}$, entonces $Valor = \frac{Saldo}{LTV}$.

In [174]:
np.random.seed(42)
n_prestamos = 5000
saldos = np.random.randint(50000, 300001, n_prestamos)
#Sumamos la media habiendo multiplicado por la desviación típica
LTV=0.70+(np.random.randn(n_prestamos)*0.10)
#LTV=np.random.normal(0.7,0.1,5000)
valor_propiedades=saldos/LTV
print(valor_propiedades)



[275097.89371801 268148.01021152 257026.05015453 ... 464118.29339123
 340189.23780249 200535.78533042]


**Ejercicio 2: Escenario de Estrés (Operaciones Vectorizadas)**

El escenario de crisis plantea dos problemas simultáneos:
1. Caída del mercado inmobiliario: El valor de todas las casas cae un 20%.
2. Subida de tipos: Los clientes tienen menos liquidez y su Probabilidad de Default (PD) aumenta.

**Instrucciones:**

1. Crea un nuevo array llamado valor_crisis que sea el valor original de las casas menos el 20%.
2. Calcula el Nuevo LTV tras la caída: $Nuevo\_LTV = \frac{Saldo}{valor\_crisis}$.
3. Calcula la Exposición en Pérdida (EAD): Solo nos interesa el dinero en riesgo de las hipotecas donde el Nuevo_LTV es mayor a 1 (esto significa que la deuda es mayor que el valor de la casa).

In [ ]:
valor_crisis=valor_propiedades*0.80
Nuevo_LTV=saldos/valor_crisis
#Esto será un array lleno de booleanos, True si el LTV es mayor que 1, False si no lo es
#donde True equivale a 1, y False a 0, por lo que al hacer la suma nos dará 
#el número de True, el número de hipotecas donde la deuda supera el valor de la casa
EAD=Nuevo_LTV>1
print(EAD)



[False False False ... False False  True]


**Ejercicio 3: Análisis y Resultados (Filtrado y Estadísticos)**

Responde a las siguientes preguntas usando funciones de NumPy:
1. ¿Cuál es el LTV promedio antes y después de la crisis?
2. ¿Cuántas hipotecas tienen ahora una deuda mayor al valor de la casa (Nuevo_LTV > 1)?
3. Pérdida Esperada: Si asumimos que los clientes con Nuevo_LTV > 1.2 van a dejar de pagar con total seguridad, ¿cuál es la suma total de dinero que el banco perdería? (Suma de los saldos de esos clientes).

In [171]:
#Simplemente usamos mean para calcular la media de LTV y Nuevo_LTV
print(f"LTV Promedio Original: {LTV.mean():.2%}")
print(f"LTV Promedio en Crisis: {Nuevo_LTV.mean():.2%}")

#Para calcular el nº de hipotecas en riesgo aplicamos sum para que contabilice 
#el número de True dentro del array EAD, el cual nos dice si se supera la condición
#de riesgo de impago
num_en_riesgo=np.sum(EAD)
print(f"Hipotecas donde la deuda supera el valor de la casa: {num_en_riesgo}")

#Como debemos sumar los saldos de aquellos clientes que asumimos que no podrán pagar
#hacemos un filtrado de saldos donde nos quedamos con los que cumplen la condición
#de riesgo de impago y después sumamos todos esos saldos.
#Además conntabilizamos la cantidad de clientes que dejarán de pagar 
#midiendo la cantidad de saldos que hay en el array filtrado.  
morosos=saldos[Nuevo_LTV>1.2]
perdida_total=np.sum(morosos)
print(f"Número de clientes que dejarán de pagar: {len(morosos)}")
print(f"Perdida Total: {perdida_total}")


LTV Promedio Original: 70.10%
LTV Promedio en Crisis: 87.62%
Hipotecas donde la deuda supera el valor de la casa: 808
Número de clientes que dejarán de pagar: 23
Perdida Total: 3893374


## ✅ SOLUCIONES

In [ ]:
import numpy as np

# Configuración inicial para que los resultados sean siempre iguales
np.random.seed(42)

# --- SOLUCIÓN EJERCICIO 1 ---
n_prestamos = 5000
saldos = np.random.randint(50000, 300001, n_prestamos)
ltvs = 0.70 + (np.random.randn(n_prestamos) * 0.10)
valor_propiedades = saldos / ltvs

# --- SOLUCIÓN EJERCICIO 2 ---
valor_crisis = valor_propiedades * 0.80
nuevo_ltv = saldos / valor_crisis

# --- SOLUCIÓN EJERCICIO 3 ---
# 1. Promedios
print(f"LTV Promedio Original: {ltvs.mean():.2%}")
print(f"LTV Promedio en Crisis: {nuevo_ltv.mean():.2%}")

# 2. Conteo de hipotecas en "Negative Equity" (Deuda > Valor)
en_riesgo = nuevo_ltv > 1
num_en_riesgo = np.sum(en_riesgo) # Los True valen 1 y los False 0
print(f"Hipotecas donde la deuda supera al valor de la casa: {num_en_riesgo}")

# 3. Pérdida Esperada (LTV > 1.2)
condicion_perdida = nuevo_ltv > 1.2
saldos_perdidos = saldos[condicion_perdida] # Filtrado booleano
total_perdida = np.sum(saldos_perdidos)

print(f"Número de clientes en default crítico: {len(saldos_perdidos)}")
print(f"Pérdida Total Estimada: {total_perdida:,.2f} €")